### ISSUE TITLE
Why not use apt-get for youtube-dl?

### ISSUE THREAD

**Issue by KuenzelIT** [shibby/owncloud-youtubedl#16]
Hey,

I'm just curious why I shouldn't use apt-get to install youtube-dl as said in the Readme:
"Do not install with your package manager such as apt-get."

Thanks!

PS: Do you think there are a lot of changes needed to make it compatible to OC9?

**Comment by shibby** [comment]
Hello,

youtube-dl binaries are old at Ubuntu/Debian repositories. You have to use latest version for not getting error when youtube-dl download operations. otherwise, download process gives error because of it's old. (btw, you can update youtube-dl binaries with "youtube-dl -U" command.)

i think, there is not so many changes for compability OC9. but for me, problem is, i can't set up development environment, and i dont have much time for this :/

**Comment by KuenzelIT** [comment]
Hey, thanks for the quick response. Alright, maybe I'll look into it, cause I think it would be very nice to have this feature in OC.
